### ISSUE TITLE
Graph generation code errors

### ISSUE THREAD

**Issue by Skwiwel** [cvignac/Top-N#1]
Hi,

I'm trying to run and experiment with your code for graph generation. Unfortunately, the code under `molecule_generation/graph_main.py` doesn't seem to be complete. Among other smaller issues, it's missing a configuration file:  
https://github.com/cvignac/Top-N/blob/main/molecule_generation/graph_main.py#L36

Would it be possible to include it?

Thanks, Skwiwel

**Comment by cvignac** [comment]
Hello Skwiwel,
I have fixed the path issues and added the missing config file.

Best,
Clément
